import { useEffect, useState } from "react";
import { Sidebar, type ViewKey } from "@/components/appigen/Sidebar";
import { PromptPanel } from "@/components/appigen/PromptPanel";
import { PreviewPanel } from "@/components/appigen/PreviewPanel";
import { DashboardPage } from "@/components/appigen/pages/DashboardPage";
import { MyAppsPage } from "@/components/appigen/pages/MyAppsPage";
import { TemplatesPage } from "@/components/appigen/pages/TemplatesPage";
import { ApiSettingsPage } from "@/components/appigen/pages/ApiSettingsPage";
import { PricingPage } from "@/components/appigen/pages/PricingPage";
import { AuthModal } from "@/components/appigen/AuthModal";
import { PricingModal } from "@/components/appigen/PricingModal";
import { SettingsPanel } from "@/components/appigen/SettingsPanel";
import { NotificationsMenu } from "@/components/appigen/NotificationsMenu";
import { GithubModal } from "@/components/appigen/GithubModal";
import { useApp } from "@/components/appigen/AppContext";
import { Sparkles, Pencil } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { ResizablePanelGroup, ResizablePanel, ResizableHandle } from "@/components/ui/resizable";
import JSZip from "jszip";

const VIEW_TITLES: Record<ViewKey, string> = {
  studio: "",
  dashboard: "Dashboard",
  apps: "My Apps",
  templates: "Templates",
  api: "API Settings",
  pricing: "Pricing & Credits",
};

const DEFAULT_PROMPT =
  "Build a minimalist task manager with drag-and-drop columns, calm color palette, and keyboard shortcuts.";

function buildDocFromPrompt(prompt: string, code?: string) {
  const safePrompt = (prompt || "Untitled App").replace(/</g, "&lt;");
  const reactSource =
    code ??
    `function App() {
  const [tasks, setTasks] = React.useState([
    { id: 1, title: "Sketch the layout", done: true },
    { id: 2, title: "Wire up state", done: false },
    { id: 3, title: "Polish the UI", done: false },
  ]);
  const toggle = (id) =>
    setTasks(tasks.map(t => t.id === id ? { ...t, done: !t.done } : t));
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-8">
      <div className="max-w-xl mx-auto">
        <div className="text-xs uppercase tracking-widest text-indigo-400">Generated by AppiGen</div>
        <h1 className="mt-1 text-3xl font-bold">${safePrompt}</h1>
        <p className="mt-2 text-sm text-slate-400">A live React component running inside a sandboxed iframe.</p>
        <ul className="mt-6 space-y-2">
          {tasks.map(t => (
            <li key={t.id}
              onClick={() => toggle(t.id)}
              className={"flex items-center gap-3 rounded-xl border border-slate-800 bg-slate-900/60 p-3.5 cursor-pointer transition hover:border-indigo-500/60 " + (t.done ? "opacity-60" : "")}>
              <span className={"h-5 w-5 rounded-md border-2 flex items-center justify-center " + (t.done ? "bg-indigo-500 border-indigo-500" : "border-slate-700")}>
                {t.done && <span className="text-[11px]">✓</span>}
              </span>
              <span className={t.done ? "line-through" : ""}>{t.title}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
ReactDOM.createRoot(document.getElementById("root")).render(<App />);`;

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>AppiGen Preview</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <style>
    html, body { background: #020617; color: #e2e8f0; margin: 0; }
    ::-webkit-scrollbar { width: 8px; height: 8px; }
    ::-webkit-scrollbar-thumb { background: #1e293b; border-radius: 999px; }
  </style>
</head>
<body>
  <div id="root"></div>
  <script type="text/babel" data-presets="react">
${reactSource}
  </script>
</body>
</html>`;
}

const slugify = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "untitled";

const Index = () => {
  const [isBuilding, setIsBuilding] = useState(false);
  const [prompt, setPrompt] = useState(DEFAULT_PROMPT);
  const [doc, setDoc] = useState<string>(() => buildDocFromPrompt(DEFAULT_PROMPT));
  const [view, setView] = useState<ViewKey>("studio");
  const [authOpen, setAuthOpen] = useState(false);
  const [pricingOpen, setPricingOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [githubOpen, setGithubOpen] = useState(false);
  const [projectTitle, setProjectTitle] = useState("Untitled Project");
  const [editingTitle, setEditingTitle] = useState(false);
  const [lastCode, setLastCode] = useState<string | null>(null);
  const { user, addNotification } = useApp();

  useEffect(() => {
    if (!user) {
      const t = setTimeout(() => setAuthOpen(true), 600);
      return () => clearTimeout(t);
    }
  }, [user]);

  const handleDownload = async () => {
    try {
      const zip = new JSZip();
      zip.file("index.html", doc);
      if (lastCode) zip.file("app.jsx", lastCode);
      zip.file("README.md", `# ${projectTitle}\n\nGenerated by AppiGen Studio.\n\n## Prompt\n${prompt}\n`);
      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url; a.download = `${slugify(projectTitle)}.zip`;
      document.body.appendChild(a); a.click(); a.remove();
      URL.revokeObjectURL(url);
      toast({ title: "📦 ZIP ready", description: `${slugify(projectTitle)}.zip` });
    } catch (e: any) {
      toast({ title: "Download failed", description: e?.message ?? "Unknown error", variant: "destructive" });
    }
  };

  const handleBuild = async (system?: string, stage?: string) => {
    const trimmed = prompt.trim();
    if (!trimmed) {
      toast({ title: "Prompt is empty", description: "Describe the app you want to build first.", variant: "destructive" });
      return;
    }
    setIsBuilding(true);
    try {
      const { data, error } = await supabase.functions.invoke("Appigen", { body: { prompt: trimmed, system, stage } });
      if (error) throw error;
      if (!data?.code) throw new Error("No code returned from AI");
      setLastCode(data.code);
      setDoc(buildDocFromPrompt(trimmed, data.code));

      // Auto-derive title if user kept default
      const finalTitle =
        projectTitle && projectTitle !== "Untitled Project"
          ? projectTitle
          : trimmed.split(/\s+/).slice(0, 6).join(" ").slice(0, 60) || "Untitled Project";
      if (finalTitle !== projectTitle) setProjectTitle(finalTitle);

      if (user) {
        const { data: auth } = await supabase.auth.getUser();
        const uid = auth.user?.id;
        if (uid) {
          const { error: insertErr } = await supabase.from("projects").insert({
            user_id: uid, title: finalTitle, prompt: trimmed, code: data.code, thumbnail: null,
          });
          if (insertErr) console.error("Save project failed:", insertErr);
        }
      }

      addNotification({ kind: "build", title: "App Built Successfully", description: finalTitle });
      toast({
        title: "✨ Build successful",
        description: user ? `Saved: "${finalTitle}"` : `Sign in to save: "${finalTitle}"`,
      });
    } catch (err: any) {
      console.error("Build failed:", err);
      toast({ title: "Build failed", description: err?.message || "Something went wrong calling the AI.", variant: "destructive" });
    } finally {
      setIsBuilding(false);
    }
  };

  return (
    <div className="flex h-screen flex-col overflow-hidden bg-background text-foreground">
      <div className="flex flex-1 overflow-hidden">
        <Sidebar
          active={view}
          onChange={setView}
          onOpenSettings={() => setSettingsOpen(true)}
          onOpenSignIn={() => setAuthOpen(true)}
          onOpenPricing={() => setPricingOpen(true)}
        />

        <div className="flex flex-1 flex-col overflow-hidden">
          <header className="relative z-30 flex h-16 shrink-0 items-center justify-between border-b border-border/60 bg-background/40 px-6 backdrop-blur-xl">
            <div className="flex min-w-0 items-center gap-3">
              {view === "studio" ? (
                editingTitle ? (
                  <input
                    autoFocus
                    value={projectTitle}
                    onChange={(e) => setProjectTitle(e.target.value)}
                    onBlur={() => setEditingTitle(false)}
                    onKeyDown={(e) => { if (e.key === "Enter" || e.key === "Escape") setEditingTitle(false); }}
                    className="rounded-md border border-primary/40 bg-background/60 px-2 py-1 font-display text-base font-semibold text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
                  />
                ) : (
                  <button onClick={() => setEditingTitle(true)} className="group flex items-center gap-2">
                    <h1 className="max-w-[40ch] truncate font-display text-base font-semibold text-foreground">{projectTitle}</h1>
                    <Pencil className="h-3 w-3 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100" />
                  </button>
                )
              ) : (
                <h1 className="font-display text-base font-semibold text-foreground">{VIEW_TITLES[view]}</h1>
              )}
              {view === "studio" && (
                <span className="rounded-md border border-primary/30 bg-primary/10 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider text-primary">Draft</span>
              )}
            </div>
            <div className="flex items-center gap-2">
              <NotificationsMenu />
              <button
                onClick={() => setPricingOpen(true)}
                className="flex h-9 items-center gap-2 rounded-lg bg-gradient-primary px-3.5 text-xs font-semibold text-primary-foreground shadow-glow transition-smooth hover:brightness-110"
              >
                <Sparkles className="h-3.5 w-3.5" />
                Upgrade
              </button>
            </div>
          </header>

          <main className="relative z-0 flex flex-1 flex-col overflow-hidden lg:flex-row">
            {view === "studio" && (
              <ResizablePanelGroup direction="horizontal" className="hidden lg:flex h-full w-full">
                <ResizablePanel defaultSize={42} minSize={25} maxSize={65} className="overflow-y-auto">
                  <PromptPanel
                    prompt={prompt}
                    onPromptChange={setPrompt}
                    onBuild={handleBuild}
                    onDownload={handleDownload}
                    isBuilding={isBuilding}
                  />
                </ResizablePanel>
                <ResizableHandle withHandle className="bg-border/60 hover:bg-primary/40 transition-colors" />
                <ResizablePanel defaultSize={58} minSize={35} className="min-h-0">
                  <PreviewPanel
                    isBuilding={isBuilding}
                    doc={doc}
                    code={lastCode}
                    onPushToGithub={() => setGithubOpen(true)}
                    onCodeChange={(newCode) => {
                      setLastCode(newCode);
                      setDoc(buildDocFromPrompt(prompt, newCode));
                    }}
                  />
                </ResizablePanel>
              </ResizablePanelGroup>
            )}
            {view === "studio" && (
              <div className="flex flex-1 flex-col lg:hidden overflow-y-auto pb-32">
                <PromptPanel
                  prompt={prompt}
                  onPromptChange={setPrompt}
                  onBuild={handleBuild}
                  onDownload={handleDownload}
                  isBuilding={isBuilding}
                />
                <div className="min-h-[60vh]">
                  <PreviewPanel
                    isBuilding={isBuilding}
                    doc={doc}
                    code={lastCode}
                    onPushToGithub={() => setGithubOpen(true)}
                    onCodeChange={(newCode) => {
                      setLastCode(newCode);
                      setDoc(buildDocFromPrompt(prompt, newCode));
                    }}
                  />
                </div>
              </div>
            )}
            {view === "dashboard" && <DashboardPage onNavigate={setView} />}
            {view === "apps" && (
              <MyAppsPage
                onNavigate={setView}
                onOpenProject={(p) => {
                  setProjectTitle(p.title);
                  setPrompt(p.prompt);
                  setLastCode(p.code);
                  setDoc(buildDocFromPrompt(p.prompt, p.code));
                  setView("studio");
                  toast({ title: "📂 Project loaded", description: p.title });
                }}
              />
            )}
            {view === "templates" && <TemplatesPage onNavigate={setView} />}
            {view === "api" && <ApiSettingsPage />}
            {view === "pricing" && <PricingPage />}
          </main>
        </div>
      </div>

      <AuthModal open={authOpen} onClose={() => setAuthOpen(false)} />
      <PricingModal open={pricingOpen} onClose={() => setPricingOpen(false)} />
      <SettingsPanel open={settingsOpen} onClose={() => setSettingsOpen(false)} />
      <GithubModal open={githubOpen} onClose={() => setGithubOpen(false)} />

      <footer className="flex h-9 shrink-0 items-center justify-between border-t border-border/60 bg-background/60 px-6 text-[11px] text-muted-foreground backdrop-blur-xl">
        <div className="flex items-center gap-3">
          <span className="flex items-center gap-1.5">
            <span className="h-1.5 w-1.5 rounded-full bg-[hsl(140_60%_55%)] shadow-[0_0_8px_hsl(140_60%_55%)]" />
            All systems operational
          </span>
          <span className="hidden sm:inline opacity-60">·</span>
          <span className="hidden font-mono opacity-70 sm:inline">v1.0.0</span>
        </div>
        <div className="font-light tracking-wide">
          © 2026 <span className="font-semibold text-foreground/80">AppiGen</span>
          <span className="mx-1.5 opacity-50">|</span>
          Powered by <span className="gradient-text font-semibold">NK</span>
        </div>
      </footer>
    </div>
  );
};

export default Index;
