import { useEffect, useRef, useState } from "react";
import { Sidebar, type ViewKey } from "@/components/appigen/Sidebar";
import { PromptPanel } from "@/components/appigen/PromptPanel";
import { PreviewPanel } from "@/components/appigen/PreviewPanel";
import { DashboardPage } from "@/components/appigen/pages/DashboardPage";
import { MyAppsPage } from "@/components/appigen/pages/MyAppsPage";
import { TemplatesPage } from "@/components/appigen/pages/TemplatesPage";
import { ApiSettingsPage } from "@/components/appigen/pages/ApiSettingsPage";
import { PricingPage } from "@/components/appigen/pages/PricingPage";
import { AuthModal } from "@/components/appigen/AuthModal";
import { PricingModal } from "@/components/appigen/PricingModal";
import { SettingsPanel } from "@/components/appigen/SettingsPanel";
import { NotificationsMenu } from "@/components/appigen/NotificationsMenu";
import { GithubModal } from "@/components/appigen/GithubModal";
import { useApp } from "@/components/appigen/AppContext";
import { Sparkles, Pencil, Menu, MessageSquare, Eye } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import JSZip from "jszip";
import { cn } from "@/lib/utils";
import { buildDocFromPrompt } from "@/lib/preview/buildDocFromPrompt";
import { buildErrorDoc } from "@/lib/preview/buildErrorDoc";

const VIEW_TITLES: Record<ViewKey, string> = {
  studio: "",
  dashboard: "Dashboard",
  apps: "My Apps",
  templates: "Templates",
  api: "API Settings",
  pricing: "Pricing & Credits",
};

const DEFAULT_PROMPT =
  "Build a minimalist task manager with drag-and-drop columns, calm color palette, and keyboard shortcuts.";

const slugify = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "untitled";

const Index = () => {
  const [isBuilding, setIsBuilding] = useState(false);
  const [prompt, setPrompt] = useState("");
  const [doc, setDoc] = useState<string>(() => buildDocFromPrompt(DEFAULT_PROMPT));
  const [view, setView] = useState<ViewKey>("studio");
  const [authOpen, setAuthOpen] = useState(false);
  const [pricingOpen, setPricingOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [githubOpen, setGithubOpen] = useState(false);
  const [projectTitle, setProjectTitle] = useState("Untitled Project");
  const [editingTitle, setEditingTitle] = useState(false);
  const [lastCode, setLastCode] = useState<string | null>(null);
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const [mobileStudioTab, setMobileStudioTab] = useState<"chat" | "preview">("chat");
  const { user, addNotification } = useApp();

  // Phase 9: auto-repair loop. Tracks attempts per code revision.
  const repairAttemptsRef = useRef(0);
  const lastReportedRef = useRef<string>("");
  const isRepairingRef = useRef(false);

  // Listen for runtime/compile errors from preview iframe and auto-repair
  useEffect(() => {
    const onMsg = async (ev: MessageEvent) => {
      const previewWindow = document.querySelector<HTMLIFrameElement>('iframe[title="AppiGen Sandbox Preview"]')?.contentWindow;
      if (!previewWindow || ev.source !== previewWindow) return;
      const m = ev.data;
      if (!m || typeof m !== "object" || !m.__appigen) return;
      const sig = `${m.kind}::${m.message}`;
      if (sig === lastReportedRef.current) return;
      lastReportedRef.current = sig;
      if (!lastCode || isRepairingRef.current) return;
      if (repairAttemptsRef.current >= 2) return; // max 2 auto attempts
      // Only repair on real failures
      if (!["error", "compile", "promise", "blank"].includes(m.kind)) return;

      repairAttemptsRef.current += 1;
      isRepairingRef.current = true;
      toast({ title: "🔧 Auto-repairing", description: `Attempt ${repairAttemptsRef.current}/2 — ${String(m.message).slice(0, 80)}` });
      try {
        const { data, error } = await supabase.functions.invoke("Appigen", {
          body: { mode: "repair", code: lastCode, error: `${m.kind}: ${m.message}\n${m.stack || ""}` },
        });
        if (error) throw error;
        if (data?.code) {
          lastReportedRef.current = "";
          setLastCode(data.code);
          setDoc(buildDocFromPrompt(prompt, data.code));
          toast({ title: "✅ Repair applied", description: "Re-rendering preview" });
        }
      } catch (e: any) {
        toast({ title: "Auto-repair failed", description: e?.message || "Unknown", variant: "destructive" });
      } finally {
        isRepairingRef.current = false;
      }
    };
    window.addEventListener("message", onMsg);
    return () => window.removeEventListener("message", onMsg);
  }, [lastCode, prompt]);

  const handleDownload = async () => {
    try {
      const zip = new JSZip();
      zip.file("index.html", doc);
      if (lastCode) zip.file("app.jsx", lastCode);
      zip.file("README.md", `# ${projectTitle}\n\nGenerated by AppiGen Studio.\n\n## Prompt\n${prompt}\n`);
      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url; a.download = `${slugify(projectTitle)}.zip`;
      document.body.appendChild(a); a.click(); a.remove();
      URL.revokeObjectURL(url);
      toast({ title: "📦 ZIP ready", description: `${slugify(projectTitle)}.zip` });
    } catch (e: any) {
      toast({ title: "Download failed", description: e?.message ?? "Unknown error", variant: "destructive" });
    }
  };

  const handleBuild = async (system?: string, stage?: string) => {
    const trimmed = prompt.trim();
    if (!trimmed) {
      toast({ title: "Prompt is empty", description: "Describe the app you want to build first.", variant: "destructive" });
      return;
    }
    repairAttemptsRef.current = 0;
    lastReportedRef.current = "";
    isRepairingRef.current = false;
    setIsBuilding(true);
    try {
      const { data, error } = await supabase.functions.invoke("Appigen", { body: { prompt: trimmed, system, stage } });
      if (error) throw error;
      if (!data?.code) throw new Error("No code returned from AI");
      setLastCode(data.code);
      setDoc(buildDocFromPrompt(trimmed, data.code));
      setMobileStudioTab("preview");

      // Auto-derive title if user kept default
      const finalTitle =
        projectTitle && projectTitle !== "Untitled Project"
          ? projectTitle
          : trimmed.split(/\s+/).slice(0, 6).join(" ").slice(0, 60) || "Untitled Project";
      if (finalTitle !== projectTitle) setProjectTitle(finalTitle);

      if (user) {
        const { data: auth } = await supabase.auth.getUser();
        const uid = auth.user?.id;
        if (uid) {
          const { error: insertErr } = await supabase.from("projects").insert({
            user_id: uid, title: finalTitle, prompt: trimmed, code: data.code, thumbnail: null,
          });
          if (insertErr) console.error("Save project failed:", insertErr);
        }
      }

      addNotification({ kind: "build", title: "App Built Successfully", description: finalTitle });
      toast({
        title: "✨ Build successful",
        description: user ? `Saved: "${finalTitle}"` : `Sign in to save: "${finalTitle}"`,
      });
    } catch (err: any) {
      console.error("Build failed:", err);
      const msg = err?.message || err?.error?.message || "Something went wrong calling the AI.";
      setDoc(buildErrorDoc(trimmed, msg));
      toast({ title: "Build failed", description: msg, variant: "destructive" });
    } finally {
      setIsBuilding(false);
    }
  };

  return (
    <div className="flex h-dvh flex-col overflow-hidden bg-background text-foreground">
      <div className="flex flex-1 overflow-hidden">
        <Sidebar
          active={view}
          onChange={setView}
          onOpenSettings={() => setSettingsOpen(true)}
          onOpenSignIn={() => setAuthOpen(true)}
          onOpenPricing={() => setPricingOpen(true)}
          mobileOpen={mobileNavOpen}
          onMobileClose={() => setMobileNavOpen(false)}
        />

        <div className="flex flex-1 flex-col overflow-hidden min-w-0">
          <header className="relative z-30 flex h-14 sm:h-16 shrink-0 items-center justify-between gap-2 border-b border-border/60 bg-background/40 px-3 sm:px-6 backdrop-blur-xl">
            <div className="flex min-w-0 items-center gap-2 sm:gap-3">
              <button
                onClick={() => setMobileNavOpen(true)}
                aria-label="Open menu"
                className="flex h-10 w-10 items-center justify-center rounded-lg text-muted-foreground transition-smooth hover:bg-secondary hover:text-foreground md:hidden"
              >
                <Menu className="h-5 w-5" />
              </button>
              {view === "studio" ? (
                editingTitle ? (
                  <input
                    autoFocus
                    value={projectTitle}
                    onChange={(e) => setProjectTitle(e.target.value)}
                    onBlur={() => setEditingTitle(false)}
                    onKeyDown={(e) => { if (e.key === "Enter" || e.key === "Escape") setEditingTitle(false); }}
                    className="w-full min-w-0 rounded-md border border-primary/40 bg-background/60 px-2 py-1 font-display text-sm sm:text-base font-semibold text-foreground focus:outline-none focus:ring-2 focus:ring-primary/30"
                  />
                ) : (
                  <button onClick={() => setEditingTitle(true)} className="group flex min-w-0 items-center gap-2">
                    <h1 className="max-w-[18ch] sm:max-w-[40ch] truncate font-display text-sm sm:text-base font-semibold text-foreground">{projectTitle}</h1>
                    <Pencil className="hidden h-3 w-3 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100 sm:block" />
                  </button>
                )
              ) : (
                <h1 className="truncate font-display text-sm sm:text-base font-semibold text-foreground">{VIEW_TITLES[view]}</h1>
              )}
              {view === "studio" && (
                <span className="hidden rounded-md border border-primary/30 bg-primary/10 px-2 py-0.5 text-[10px] font-medium uppercase tracking-wider text-primary sm:inline">Draft</span>
              )}
            </div>
            <div className="flex shrink-0 items-center gap-1 sm:gap-2">
              <NotificationsMenu />
              <button
                onClick={() => setPricingOpen(true)}
                className="flex h-9 items-center gap-1.5 rounded-lg bg-gradient-primary px-2.5 sm:px-3.5 text-xs font-semibold text-primary-foreground shadow-glow transition-smooth hover:brightness-110"
              >
                <Sparkles className="h-3.5 w-3.5" />
                <span className="hidden sm:inline">Upgrade</span>
              </button>
            </div>
          </header>

          <main className="relative z-0 flex flex-1 flex-col overflow-hidden">
            {view === "studio" && (
              <>
                {/* Mobile tab switcher */}
                <div className="flex shrink-0 items-center gap-1 border-b border-border/60 bg-background/60 p-1.5 lg:hidden">
                  <button
                    onClick={() => setMobileStudioTab("chat")}
                    className={cn(
                      "flex flex-1 items-center justify-center gap-1.5 rounded-md px-3 py-2 text-xs font-semibold transition-smooth",
                      mobileStudioTab === "chat"
                        ? "bg-primary text-primary-foreground shadow-soft"
                        : "text-muted-foreground hover:text-foreground"
                    )}
                  >
                    <MessageSquare className="h-3.5 w-3.5" />
                    Prompt
                  </button>
                  <button
                    onClick={() => setMobileStudioTab("preview")}
                    className={cn(
                      "flex flex-1 items-center justify-center gap-1.5 rounded-md px-3 py-2 text-xs font-semibold transition-smooth",
                      mobileStudioTab === "preview"
                        ? "bg-primary text-primary-foreground shadow-soft"
                        : "text-muted-foreground hover:text-foreground"
                    )}
                  >
                    <Eye className="h-3.5 w-3.5" />
                    Preview
                  </button>
                </div>

                <div className="flex min-h-0 flex-1 flex-col lg:flex-row">
                  <section
                    className={cn(
                      "min-h-0 overflow-y-auto border-b border-border/60 lg:w-[42%] lg:border-b-0 lg:border-r lg:flex",
                      mobileStudioTab === "chat" ? "flex flex-1 flex-col" : "hidden lg:flex"
                    )}
                  >
                    <PromptPanel
                      prompt={prompt}
                      onPromptChange={setPrompt}
                      onBuild={handleBuild}
                      onDownload={handleDownload}
                      isBuilding={isBuilding}
                    />
                  </section>
                  <section
                    className={cn(
                      "min-h-0 flex-1 lg:flex",
                      mobileStudioTab === "preview" ? "flex" : "hidden lg:flex"
                    )}
                  >
                    <PreviewPanel
                      isBuilding={isBuilding}
                      doc={doc}
                      code={lastCode}
                      onPushToGithub={() => setGithubOpen(true)}
                      onCodeChange={(newCode) => {
                        repairAttemptsRef.current = 0;
                        lastReportedRef.current = "";
                        isRepairingRef.current = false;
                        setLastCode(newCode);
                        setDoc(buildDocFromPrompt(prompt, newCode));
                      }}
                    />
                  </section>
                </div>
              </>
            )}
            {view === "dashboard" && <DashboardPage onNavigate={setView} />}
            {view === "apps" && (
              <MyAppsPage
                onNavigate={setView}
                onOpenProject={(p) => {
                  setProjectTitle(p.title);
                  repairAttemptsRef.current = 0;
                  lastReportedRef.current = "";
                  isRepairingRef.current = false;
                  setPrompt(p.prompt);
                  setLastCode(p.code);
                  setDoc(buildDocFromPrompt(p.prompt, p.code));
                  setView("studio");
                  toast({ title: "📂 Project loaded", description: p.title });
                }}
              />
            )}
            {view === "templates" && <TemplatesPage onNavigate={setView} />}
            {view === "api" && <ApiSettingsPage />}
            {view === "pricing" && <PricingPage />}
          </main>
        </div>
      </div>

      <AuthModal open={authOpen} onClose={() => setAuthOpen(false)} />
      <PricingModal open={pricingOpen} onClose={() => setPricingOpen(false)} />
      <SettingsPanel open={settingsOpen} onClose={() => setSettingsOpen(false)} />
      <GithubModal open={githubOpen} onClose={() => setGithubOpen(false)} />

      <footer className="flex h-9 shrink-0 items-center justify-between border-t border-border/60 bg-background/60 px-6 text-[11px] text-muted-foreground backdrop-blur-xl">
        <div className="flex items-center gap-3">
          <span className="flex items-center gap-1.5">
            <span className="h-1.5 w-1.5 rounded-full bg-[hsl(140_60%_55%)] shadow-[0_0_8px_hsl(140_60%_55%)]" />
            All systems operational
          </span>
          <span className="hidden sm:inline opacity-60">·</span>
          <span className="hidden font-mono opacity-70 sm:inline">v1.0.0</span>
        </div>
        <div className="font-light tracking-wide">
          © 2026 <span className="font-semibold text-foreground/80">AppiGen</span>
          <span className="mx-1.5 opacity-50">|</span>
          Powered by <span className="gradient-text font-semibold">NK</span>
        </div>
      </footer>
    </div>
  );
};

export default Index;
