import { parseFileMarkers } from "./parseFileMarkers";
import { sanitizeReactSource } from "./sanitizeReactSource";

const ROOT_RENDER_CALL = /ReactDOM\s*\.\s*createRoot\s*\(\s*document\s*\.\s*getElementById\s*\(\s*["']root["']\s*\)\s*\)\s*\.\s*render\s*\(\s*<App\s*\/?>\s*\)\s*;?/g;
const LEGACY_RENDER_CALL = /ReactDOM\s*\.\s*render\s*\(\s*<App\s*\/?>\s*,\s*document\s*\.\s*getElementById\s*\(\s*["']root["']\s*\)\s*\)\s*;?/g;
const BARE_CREATE_ROOT_CALL = /\bcreateRoot\s*\(\s*document\s*\.\s*getElementById\s*\(\s*["']root["']\s*\)\s*\)\s*\.\s*render\s*\(\s*<App\s*\/?>\s*\)\s*;?/g;
function escapeScriptText(src: string): string {
  return src.replace(/<\/script/gi, "<\\/script").replace(/<!--/g, "<\\!--");
}

function collectPotentialGlobals(src: string): string[] {
  const names = new Set<string>([
    "Activity", "AlertCircle", "ArrowLeft", "ArrowRight", "BarChart3", "Bell", "BookOpen", "Bot", "Calendar", "Camera",
    "Check", "CheckCircle", "ChevronDown", "ChevronLeft", "ChevronRight", "ChevronUp", "Circle", "Clock", "Code", "Copy",
    "CreditCard", "Database", "Download", "Edit", "ExternalLink", "Eye", "File", "Filter", "Folder", "Github", "Globe",
    "Heart", "Home", "Image", "Info", "Layers", "LayoutDashboard", "LineChart", "Link", "List", "Lock", "Mail", "MapPin",
    "Menu", "MessageCircle", "Mic", "Minus", "Moon", "MoreHorizontal", "MoreVertical", "PanelLeft", "Paperclip", "Pause", "Pencil",
    "Play", "Plus", "RefreshCw", "Rocket", "Save", "Search", "Send", "Settings", "Share", "Shield", "ShoppingCart",
    "Sparkles", "Star", "Sun", "Trash", "TrendingUp", "Upload", "User", "Users", "Wand2", "X", "Zap"
  ]);
  for (const match of src.matchAll(/<\s*([A-Z][A-Za-z0-9_]*)\b/g)) {
    if (match[1] !== "App" && match[1] !== "React.Fragment") names.add(match[1]);
  }
  return Array.from(names).sort();
}

const DEFAULT_APP_CODE = `function App() {
  const [tasks, setTasks] = React.useState([
    { id: 1, title: "Sketch the layout", done: true },
    { id: 2, title: "Wire up state", done: false },
    { id: 3, title: "Polish the UI", done: false },
  ]);
  const toggle = (id) =>
    setTasks(tasks.map(t => t.id === id ? { ...t, done: !t.done } : t));
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-8">
      <div className="max-w-xl mx-auto">
        <div className="text-xs uppercase tracking-widest text-indigo-400">Generated by AppiGen</div>
        <h1 className="mt-1 text-3xl font-bold">AppiGen Studio</h1>
        <p className="mt-2 text-sm text-slate-400">A live React component running inside a sandboxed iframe.</p>
        <ul className="mt-6 space-y-2">
          {tasks.map(t => (
            <li key={t.id}
              onClick={() => toggle(t.id)}
              className={"flex items-center gap-3 rounded-xl border border-slate-800 bg-slate-900/60 p-3.5 cursor-pointer transition hover:border-indigo-500/60 " + (t.done ? "opacity-60" : "")}>
              <span className={"h-5 w-5 rounded-md border-2 flex items-center justify-center " + (t.done ? "bg-indigo-500 border-indigo-500" : "border-slate-700")}>
                {t.done && <span className="text-[11px]">\u2713</span>}
              </span>
              <span className={t.done ? "line-through" : ""}>{t.title}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
export default App;`;
// Softer strip — keeps ES import/export so Babel's env preset can transform them.
function stripModuleSyntaxKeepImports(src: string): string {
  let out = (src || "").replace(/\r\n/g, "\n");
  out = out.replace(/^\s*```(?:jsx|tsx|js|ts|javascript|typescript)?\s*/i, "").replace(/```\s*$/i, "");
  // Remove any residual ReactDOM.createRoot(...).render(<App/>) — the loader mounts the default export.
  out = out.replace(ROOT_RENDER_CALL, "").replace(LEGACY_RENDER_CALL, "").replace(BARE_CREATE_ROOT_CALL, "");
  return out.trim();
}
export function buildDocFromPrompt(prompt: string, code?: string) {
  const safePrompt = (prompt || "Untitled App").replace(/</g, "&lt;");
  const raw = code ?? DEFAULT_APP_CODE;

  // Multi-file mode
  const parsed = parseFileMarkers(raw);
  let files: Record<string, string>;
  let entry: string;
  if (parsed) {
    files = {};
    for (const [p, c] of Object.entries(parsed.files)) files[p] = stripModuleSyntaxKeepImports(c);
    entry = parsed.entry;
  } else {
    // Legacy single-file: strip module syntax fully so it can execute inline
    const sanitized = sanitizeReactSource(raw);
    files = { "src/App.jsx": sanitized };
    entry = "src/App.jsx";
  }

  // Collect icon globals across all files for lucide fallbacks
  const iconGlobals = collectPotentialGlobals(Object.values(files).join("\n"));

  const runtimeShield = `
(function(){
  var hasMounted = false;
  function report(kind, message, stack){
    try { parent.postMessage({ __appigen: true, kind: kind, message: String(message||''), stack: String(stack||'') }, '*'); } catch(e){}
    var host = document.getElementById('__appigen_err');
    if(!host){
      host = document.createElement('div');
      host.id = '__appigen_err';
      host.style.cssText = 'position:fixed;left:12px;right:12px;bottom:12px;z-index:99999;font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;background:rgba(127,29,29,.95);color:#fee2e2;border:1px solid rgba(248,113,113,.6);border-radius:10px;padding:12px 14px;max-height:45vh;overflow:auto;box-shadow:0 12px 40px rgba(0,0,0,.5);backdrop-filter:blur(8px);';
      document.body && document.body.appendChild(host);
    }
    host.innerHTML = '<div style="font-weight:700;color:#fecaca;margin-bottom:4px">\u26A0 Runtime '+kind+'</div><div style="white-space:pre-wrap;word-break:break-word">'+(message||'')+'</div>'+(stack?'<details style="margin-top:6px;opacity:.85"><summary style="cursor:pointer">stack</summary><pre style="white-space:pre-wrap">'+stack+'</pre></details>':'');
  }
  window.addEventListener('error', function(e){ report('error', e.message, e.error && e.error.stack); });
  window.addEventListener('unhandledrejection', function(e){ var r = e.reason || {}; report('promise', r.message || r, r.stack); });
  var _ce = console.error;
  console.error = function(){ try { report('console', Array.prototype.slice.call(arguments).map(String).join(' '), ''); } catch(_){ } _ce.apply(console, arguments); };
  setTimeout(function(){
    var root = document.getElementById('root');
    if(root && !hasMounted && root.childElementCount === 0 && !document.getElementById('__appigen_err')){
      report('blank', 'Preview rendered nothing within 2.5s', '');
    }
  }, 2500);
  window.__appigenMarkMounted = function(){ hasMounted = true; };
})();
`;

  const filesJSON = JSON.stringify(files);
  const entryJSON = JSON.stringify(entry);
  const iconsJSON = JSON.stringify(iconGlobals);

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>AppiGen Preview — ${safePrompt}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script crossorigin src="https://unpkg.com/react@18/umd/react.development.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.development.js"></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <style>
    html, body { background: #020617; color: #e2e8f0; margin: 0; }
    ::-webkit-scrollbar { width: 8px; height: 8px; }
    ::-webkit-scrollbar-thumb { background: #1e293b; border-radius: 999px; }
  </style>
  <script>${runtimeShield}</script>
</head>
<body>
  <div id="root"></div>
  <script>
(function(){
  window.useState = React.useState; window.useEffect = React.useEffect;
  window.useRef = React.useRef; window.useMemo = React.useMemo;
  window.useCallback = React.useCallback; window.useReducer = React.useReducer;
  window.useContext = React.useContext; window.Fragment = React.Fragment;

  window.__appigenIcon = function(name){
    return React.forwardRef(function AppiGenIcon(props, ref){
      props = props || {};
      var size = props.size || 20, sw = props.strokeWidth || 2, cn = props.className || '';
      var rest = Object.assign({}, props); delete rest.size; delete rest.strokeWidth; delete rest.className;
      return React.createElement('svg', Object.assign({ ref: ref, xmlns: 'http://www.w3.org/2000/svg', width: size, height: size, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: sw, strokeLinecap: 'round', strokeLinejoin: 'round', className: cn, 'aria-hidden': 'true', 'data-icon': name }, rest),
        React.createElement('circle', { cx: 12, cy: 12, r: 8 }),
        React.createElement('path', { d: 'M12 8v8M8 12h8' }));
    });
  };
  ${iconsJSON}.forEach(function(n){ if(!window[n]) window[n] = window.__appigenIcon(n); });

  var lucideProxy = new Proxy({}, { get: function(_, k){
    var key = String(k);
    if (key === '__esModule') return true;
    return window[key] || window.__appigenIcon(key);
  }});

  var RouterContext = React.createContext({ path: '/' });
  function BrowserRouter(props){
    return React.createElement(RouterContext.Provider, { value: { path: '/' } }, props && props.children);
  }
  function Routes(props){
    var children = React.Children.toArray(props && props.children);
    var selected = children.find(function(child){
      return child && child.props && (child.props.path === '/' || child.props.index || child.props.path === '*');
    }) || children[0] || null;
    return selected && selected.props ? (selected.props.element || selected.props.children || null) : null;
  }
  function Route(props){ return props.element || props.children || null; }
  function Link(props){
    var rest = Object.assign({}, props || {});
    var to = rest.to || '#';
    delete rest.to;
    return React.createElement('a', Object.assign({ href: String(to) }, rest), props && props.children);
  }
  function NavLink(props){ return React.createElement(Link, props, props && props.children); }
  function Outlet(){ return null; }
  function useNavigate(){ return function(){}; }
  function useLocation(){ return { pathname: '/', search: '', hash: '', state: null, key: 'default' }; }
  function useParams(){ return {}; }

  // ========= Virtual Module System =========
  var FILES = ${filesJSON};
  var CACHE = Object.create(null);

  function normalize(p){
    var parts = p.split('/'), out = [];
    for (var i=0;i<parts.length;i++){
      var s = parts[i];
      if (!s || s === '.') continue;
      if (s === '..') out.pop(); else out.push(s);
    }
    return out.join('/');
  }
  function dirname(p){ var i = p.lastIndexOf('/'); return i<0? '' : p.slice(0, i); }

  var EXT_MODULES = {
    'react': React,
    'react-dom': ReactDOM,
    'react-dom/client': ReactDOM,
    'lucide-react': lucideProxy,
    'react-router-dom': { BrowserRouter: BrowserRouter, HashRouter: BrowserRouter, MemoryRouter: BrowserRouter, Routes: Routes, Route: Route, Link: Link, NavLink: NavLink, Outlet: Outlet, useNavigate: useNavigate, useLocation: useLocation, useParams: useParams },
  };

  function resolveSpec(fromPath, spec){
    if (spec in EXT_MODULES) return { ext: EXT_MODULES[spec] };
    // Ignore unknown bare packages gracefully
    if (!/^[.@]/.test(spec) && !spec.startsWith('/')) {
      // heuristic: node_modules-like -> empty module
      return { ext: new Proxy(function(){}, { get: function(){ return function(){ return null; }; } }) };
    }
    var target = spec;
    if (spec.startsWith('@/')) target = 'src/' + spec.slice(2);
    else if (spec.startsWith('./') || spec.startsWith('../')) target = normalize(dirname(fromPath) + '/' + spec);
    else if (spec.startsWith('/')) target = normalize(spec.slice(1));
    var cands = [target, target+'.jsx', target+'.js', target+'.tsx', target+'.ts', target+'/index.jsx', target+'/index.js', target+'/index.tsx'];
    for (var i=0;i<cands.length;i++) if (FILES[cands[i]] != null) return { file: cands[i] };
    // fallback: empty
    return { ext: {} };
  }

  function makeRequire(fromPath){
    return function(spec){
      var r = resolveSpec(fromPath, spec);
      if ('ext' in r) return r.ext;
      return loadFile(r.file);
    };
  }

  function loadFile(path){
    if (CACHE[path]) return CACHE[path].exports;
    var src = FILES[path];
    if (src == null) throw new Error('Module not found: '+path);
    var compiled;
    try {
      compiled = Babel.transform(src, {
        presets: [
          ['env', { modules: 'commonjs', targets: { esmodules: true } }],
          ['react', { runtime: 'classic' }],
        ],
        filename: path,
        sourceType: 'module',
      }).code;
    } catch (e) {
      throw new Error('Compile error in '+path+': '+(e && e.message ? e.message : e));
    }
    var module = { exports: {} };
    CACHE[path] = module;
    var fn;
    try {
      fn = new Function('require','module','exports','React','ReactDOM', compiled);
    } catch (e) {
      throw new Error('Syntax error in '+path+': '+(e && e.message ? e.message : e));
    }
    fn(makeRequire(path), module, module.exports, React, ReactDOM);
    if (!module.exports.default && typeof module.exports.App === 'function') module.exports.default = module.exports.App;
    return module.exports;
  }

  function showError(msg, stack){
    parent.postMessage({ __appigen: true, kind: 'compile', message: msg, stack: stack || '' }, '*');
    var pre = document.createElement('pre');
    pre.style.cssText = 'color:#fecaca;background:#7f1d1d;padding:16px;margin:16px;border-radius:8px;white-space:pre-wrap;font:12px ui-monospace,Menlo,monospace';
    pre.textContent = 'Preview error: ' + msg + (stack ? '\\n\\n'+stack : '');
    document.body.appendChild(pre);
  }

  try {
    var entryExports = loadFile(${entryJSON});
    var App = entryExports.default || entryExports.App || entryExports;
    if (typeof App !== 'function') {
      // Entry may be a bootstrapping file that already called ReactDOM.render — that's fine.
      if (!document.getElementById('root').childElementCount) {
        throw new Error('Entry file did not export a default React component.');
      }
    } else {
      ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(App));
      if (window.__appigenMarkMounted) window.__appigenMarkMounted();
    }
  } catch (e) {
    showError(e && e.message ? e.message : String(e), e && e.stack);
  }
})();
  </script>
</body>
</html>`;
}
